import { ProcessRunner } from '@taskforge/execution';
import {
  TaskForgeDatabase,
  RunRepository,
  GoalRepository,
  TaskRepository,
  EventRepository,
  VerificationRepository,
  AuditService,
} from '@taskforge/persistence';
import { TelemetryCollector } from '@taskforge/telemetry';
import { integrationBranchName } from './branch-naming.js';

/**
 * Pushing and opening a PR are explicit, human-initiated actions performed on
 * the user's behalf (not by an agent), so they need the user's own git/gh
 * credentials (SSH agent, GH_TOKEN, credential helpers). Everything is
 * inherited except TaskForge's own router key.
 */
const USER_ACTION_ENV_POLICY = { inherit: true, denyPatterns: ['TASKFORGE_OPENAI_API_KEY'] };

export interface CreatePROptions {
  runId: string;
  title?: string;
  targetBranch?: string;
  draft?: boolean;
  repoRoot?: string;
  /** Branch to open the PR from; defaults to the run's integration branch. */
  headBranch?: string;
}

export interface PRCreationResult {
  success: boolean;
  prUrl?: string;
  summary: string;
  commandUsed: string;
  message: string;
}

export interface ImportedIssue {
  number: number;
  title: string;
  body: string;
  goalText: string;
}

export class GitHubWorkflowService {
  private auditService: AuditService;
  private verificationRepo: VerificationRepository;
  private telemetry: TelemetryCollector;

  constructor(
    private db: TaskForgeDatabase,
    private repoRoot: string = process.cwd(),
  ) {
    const runRepo = new RunRepository(this.db);
    const goalRepo = new GoalRepository(this.db);
    const taskRepo = new TaskRepository(this.db);
    const eventRepo = new EventRepository(this.db);
    this.auditService = new AuditService(runRepo, goalRepo, taskRepo, eventRepo);
    this.verificationRepo = new VerificationRepository(this.db);
    this.telemetry = new TelemetryCollector(this.db);
  }

  async isGhInstalled(): Promise<boolean> {
    try {
      const res = await ProcessRunner.run({
        command: 'which',
        args: ['gh'],
        timeoutMs: 5000,
      });
      return res.exitCode === 0;
    } catch {
      return false;
    }
  }

  generatePullRequestSummary(runId: string): string {
    const audit = this.auditService.reconstructRun(runId);
    if (!audit) {
      return `Run ${runId} not found in database.`;
    }

    const costReport = this.telemetry.getCostReport(runId);
    const runStats = this.telemetry.getRunSummary(runId);

    const lines: string[] = [
      `## 🚀 TaskForge Automated Run Summary (${runId})`,
      '',
      `**Goal:** ${audit.goal?.description ?? 'No goal recorded'}`,
      `**Final Status:** \`${audit.run.status.toUpperCase()}\``,
      '',
      '### 📋 Executed & Verified Tasks',
      '| ID | Title | Type | Status | Rework Count |',
      '| :--- | :--- | :--- | :--- | :--- |',
    ];

    for (const t of audit.tasks) {
      lines.push(
        `| \`${t.id}\` | ${t.title} | \`${t.type}\` | **${t.status.toUpperCase()}** | ${t.reworkCount} |`,
      );
    }

    lines.push('');
    lines.push('### 🛡️ Quality & Verification Evidence');
    const verifications = this.verificationRepo.listLatestByRun(runId);
    const withChecks = verifications.filter((v) => v.result.checks.length > 0);
    if (withChecks.length === 0) {
      lines.push(
        '- No automated verification results were recorded for this run (verification was disabled, not applicable, or tasks were read-only). **Do not assume tests, lint or typecheck ran.**',
      );
    } else {
      for (const { taskId, result } of withChecks) {
        const checks = result.checks
          .map((c) => `${c.success ? '✅' : '❌'} \`${c.command}\``)
          .join(' · ');
        lines.push(`- ${taskId ? `\`${taskId}\`: ` : ''}${checks}`);
      }
    }
    if (runStats) {
      lines.push(
        `- **First-pass verification rate:** ${(runStats.firstPassRate * 100).toFixed(1)}%`,
      );
      lines.push(`- **Total duration:** ${(runStats.durationMs / 1000).toFixed(1)}s`);
    }

    lines.push('');
    lines.push('### 💰 Telemetry & Resource Utilization');
    lines.push(`- **Total estimated cost:** \`$${costReport.totalCostUsd.toFixed(4)} USD\``);
    lines.push(
      `- **Tokens processed:** ${costReport.totalInputTokens.toLocaleString()} input / ${costReport.totalOutputTokens.toLocaleString()} output`,
    );

    lines.push('');
    lines.push('---');
    lines.push(
      '*Automatically generated by [TaskForge](https://github.com/eder/taskforge) control plane.*',
    );

    return lines.join('\n');
  }

  /**
   * `gh pr create --head <branch>` requires the branch to exist on the remote.
   * Pushes it (never forced). Returns an error message, or undefined on success.
   */
  private async pushBranch(branch: string, cwd: string): Promise<string | undefined> {
    const remotes = await ProcessRunner.run({
      command: 'git',
      args: ['remote'],
      cwd,
      timeoutMs: 10000,
      envPolicy: USER_ACTION_ENV_POLICY,
    });
    const names = remotes.stdout.split('\n').map((r) => r.trim()).filter(Boolean);
    if (names.length === 0) return 'this repository has no git remote configured';
    const remote = names.includes('origin') ? 'origin' : names[0];

    const push = await ProcessRunner.run({
      command: 'git',
      args: ['push', '--set-upstream', remote, branch],
      cwd,
      timeoutMs: 60000,
      envPolicy: USER_ACTION_ENV_POLICY,
    });
    return push.exitCode === 0 ? undefined : (push.stderr || push.stdout).trim();
  }

  async createPullRequest(options: CreatePROptions): Promise<PRCreationResult> {
    const runId = options.runId;
    const branchName =
      options.headBranch ??
      (options.runId.startsWith('taskforge/')
        ? options.runId
        : integrationBranchName(options.runId));

    const summary = this.generatePullRequestSummary(runId);
    const title = options.title ?? `taskforge: automated integration for ${runId}`;
    const targetBranch = options.targetBranch ?? 'main';

    const hasGh = await this.isGhInstalled();
    const commandUsed = `gh pr create --title "${title}" --base "${targetBranch}" --head "${branchName}"`;

    if (!hasGh) {
      return {
        success: false,
        summary,
        commandUsed,
        message:
          'GitHub CLI (`gh`) not found on system. PR summary generated successfully for manual submission.',
      };
    }

    const cwd = options.repoRoot ?? this.repoRoot;
    const pushError = await this.pushBranch(branchName, cwd);
    if (pushError) {
      return {
        success: false,
        summary,
        commandUsed,
        message: `Could not push ${branchName} before creating the pull request: ${pushError}`,
      };
    }

    try {
      const args = [
        'pr',
        'create',
        '--title',
        title,
        '--body',
        summary,
        '--head',
        branchName,
        '--base',
        targetBranch,
      ];
      if (options.draft) {
        args.push('--draft');
      }

      const res = await ProcessRunner.run({
        command: 'gh',
        args,
        cwd,
        timeoutMs: 30000,
        envPolicy: USER_ACTION_ENV_POLICY,
      });

      if (res.exitCode === 0) {
        const prUrl = res.stdout.trim();
        return {
          success: true,
          prUrl,
          summary,
          commandUsed,
          message: `Pull request created successfully: ${prUrl}`,
        };
      } else {
        return {
          success: false,
          summary,
          commandUsed,
          message: `Failed to execute gh pr create: ${res.stderr || res.stdout}`,
        };
      }
    } catch (err) {
      return {
        success: false,
        summary,
        commandUsed,
        message: `Error creating Pull Request via GitHub CLI: ${(err as Error).message}`,
      };
    }
  }

  async importIssue(issueNumber: number | string): Promise<ImportedIssue> {
    const num = typeof issueNumber === 'string' ? issueNumber.replace('#', '') : issueNumber;

    const res = await ProcessRunner.run({
      command: 'gh',
      args: ['issue', 'view', String(num), '--json', 'number,title,body'],
      cwd: this.repoRoot,
      timeoutMs: 15000,
      envPolicy: USER_ACTION_ENV_POLICY,
    });

    if (res.exitCode !== 0) {
      throw new Error(`Failed to fetch Issue #${num} via GitHub CLI: ${res.stderr || res.stdout}`);
    }

    const data = JSON.parse(res.stdout) as { number: number; title: string; body: string };
    const goalText = `Issue #${data.number}: ${data.title}\n\n${data.body}`;

    return {
      number: data.number,
      title: data.title,
      body: data.body,
      goalText,
    };
  }
}
