export type EventType =
  | 'RUN_CREATED'
  | 'GOAL_UPDATED'
  | 'PLAN_PROPOSED'
  | 'TASK_PREFLIGHT_STARTED'
  | 'TASK_CHALLENGED'
  | 'TASK_ACCEPTED'
  | 'TASK_COLLABORATION_RECOMMENDED'
  | 'TASK_SPLIT_RECOMMENDED'
  | 'ROUTING_REQUESTED'
  | 'ROUTING_DECIDED'
  | 'ASSIGNMENT_CREATED'
  | 'AGENT_MESSAGE_SENT'
  | 'COLLABORATION_ESCALATED'
  | 'COLLABORATION_APPROVED'
  | 'COLLABORATION_REJECTED'
  | 'COLLABORATION_DELAYED'
  | 'STAFFING_CAPPED'
  | 'TEAM_STAFFING_DEGRADED'
  | 'TEAM_CUMULATIVE_INTEGRATION'
  | 'INVESTIGATOR_FAILED'
  | 'INVESTIGATOR_REASSIGNED'
  | 'INVESTIGATOR_CAPACITY_EXHAUSTED'
  | 'INVESTIGATION_DEGRADED'
  | 'TASK_STARTED'
  | 'TASK_COMPLETED'
  | 'VERIFY_STARTED'
  | 'VERIFY_COMPLETED'
  | 'REVIEW_COMPLETED'
  | 'INTEGRATION_COMPLETED'
  | 'DELIVERY_READY'
  | 'DELIVERY_APPLIED'
  | 'DELIVERY_PR_CREATED'
  | 'DELIVERY_DISCARDED'
  | 'DELIVERY_CONFLICT'
  | 'COMPLETION_GATE_ACCEPTED'
  | 'COMPLETION_GATE_REJECTED'
  | 'PLAN_REVISED';

export interface TaskForgeEvent {
  id: string;
  runId: string;
  taskId?: string;
  type: EventType;
  payload: Record<string, unknown>;
  timestamp: Date;
}
